### ISSUE TITLE
python error with broker name regex validation

### ISSUE THREAD

**Issue by fongd** [DanielWinks/pwrstat_docker#4]
I'm getting the following errors in my container's logs when I start it:

<pre>Starting pwrstatd 1.3.2.
Traceback (most recent call last):
  File "/pwrstat_api.py", line 148, in <module>
    Pwrstat()
  File "/pwrstat_api.py", line 119, in __init__
    mqtt_schema(self.mqtt_config)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: does not match regular expression for dictionary value @ data['broker']</pre>

Here is my `pwrstat.yaml` file:

<pre>
---
mqtt:
  broker: "telegraf"
  port: 1883
  client_id: "pwrstat_mqtt"
  topic: "sensors/livingroom/power/ups"
  refresh: 3
  qos: 0
  retained: true
rest:
  port: 5002
  bind_address: "0.0.0.0"
</pre>

If I'm not mistaken, the `broker` should refer to the IP address or hostname of the MQTT consumer? (In my case, it's my telegraf container.)

**Comment by DanielWinks** [comment]
The broker IP address needs to be the IP address of your MQTT broker. This shouldn't be your telegraf container, since that's telegraf and not an MQTT broker. MQTT is a broker-based pub/sub message system. The general high-level function is that my pwrstat docker container publishes messages to the MQTT broker on a specific topic, then you subscribe to that topic on the broker from telegraf.

Basically this:
pwrstat <-> broker <-> telegraf

Note that the broker must be an IP address (ie, 192.168.1.33), not a dns name. It's best practice to not use DNS names with MQTT as dns name resolution can add dramatic overhead to MQTT messaging, both in terms of latency and total data transfer. If you run this docker container and a Mosquitto MQTT broker docker container on the same Docker host, you can use the Docker container bridge address of 172.17.0.1 here and it _should_ work.

I personally use Mosquitto as my MQTT broker. That said, I recommend HiveMQ's beginners' guides as they're quite good, and apply just as much to Mosquitto as HiveMQ (MQTT is the same, regardless of broker). Read more starting here to learn more about how MQTT works: https://www.hivemq.com/blog/mqtt-essentials-part-1-introducing-mqtt/

**Comment by fongd** [comment]
Thanks for clarifying, I'm just getting into Telegraf and am completely new to MQTT. It would be great if some additional documentation or usage examples were included to help newbies tie it all together.

That being said, it's customary to be able to refer to Docker containers by their hostnames as it eliminates the need for hardcoded IP addresses. You also have to expose the container's port in your `docker-compose.yml` file if you want to be able to access the container by IP address (even on the bridge interface)—most of my containers don't expose any. I'll have the same issue running Mosquitto as a container unless I expose its port.
