### ISSUE TITLE
The H2C device can't be used, because the linux system does not support libusb or libusb version is too old

### ISSUE THREAD

**Issue by ScanxTaz** [DanielWinks/pwrstat_docker#5]
Hey,

I installed the container and build it myself (not with compose).

I started the container with the following command :
> docker container run -p 5002:5002 --device /dev/bus/usb/001/005:/dev/bus/usb/001/001 --detach --name UPS

Currently, the container is running and connecting my MQTT server, but publishing the following value in the topic "sensors/basement/power/up" : 
> {"State": "Lost Communication"}

Looking in the logs of the container (in pwrstatd.log), i can see the following message :+1: 
`2019/11/13 22:32:08 PM	Daemon startups.
2019/11/13 22:32:08 PM	The H2C device can't be used, because the linux system does not support libusb or libusb version is too old.
`

Do you have an idea where I could search ? Thanks.

**Comment by ScanxTaz** [comment]
ok, I solved the error message by installing libusb-compat
`http://www.linuxfromscratch.org/blfs/view/8.0/general/libusb-compat.html`

but the message remains :+1: 

> root@db6fe896ed35:~/libusb-compat-0.1.5# pwrstat -status

The UPS information shows as following:


	Current UPS status:
		State........................ Lost Communication

If you have an idea, it's welcome...

**Comment by ScanxTaz** [comment]
Ok, it can be close, the container must be started with --privileged mode to access the /dev/bus/usb

working now :)

**Comment by DanielWinks** [comment]
Yep, it needs privileged mode to access USB due to how Docker works.

I'm working on a new version that will use ser2net/socat to get around this requirement, and also allow for the container to run in a cluster without needing to run on the specific node with the USB connection. That will require installing/configuring ser2net on the node with the USB device, but otherwise the container itself can be freely moved between nodes as it'll access the zwave stick via TCP instead of USB.
